# Generated by Django 3.0.2 on 2020-01-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='area_de_interesse',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='experiencia',
            field=models.BooleanField(default=True),
        ),
    ]
