# Generated by Django 3.0.2 on 2020-01-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200116_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_de_nasc',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
