# Generated by Django 3.0.2 on 2020-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_pessoa_data_de_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='area_de_interesse',
            field=models.CharField(choices=[('S', 'Saúde'), ('A', 'Assistência Social'), ('O', 'Outros')], max_length=255, verbose_name='àrea_de_interesse'),
        ),
    ]
