# Generated by Django 3.0.2 on 2020-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=255, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('quantidade_de_vagas', models.IntegerField()),
                ('cargo', models.CharField(max_length=255)),
                ('descricao_da_vaga', models.CharField(max_length=255)),
            ],
        ),
    ]
